name: Recognize Contributors
on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    runs-on: self-hosted
    name: A job to automate contrib in readme
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@1ff4c56187458b34cd602aee93e897344ce34bfc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
